server.port=8081

#Aiven MySQL Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Data JPA / Hibernate Settings
# This line  tells Spring to automatically create database tables
spring.jpa.hibernate.ddl-auto=update

#  prints the SQL commands to console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect